"""initial schema

Revision ID: 82eebe030e4d
Revises: 
Create Date: 2026-09-22 20:54:33.735733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82eebe030e4d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha_hash', sa.String(), nullable=False),
    sa.Column('foto_perfil', sa.String(), nullable=True),
    sa.Column('tipo_usuario', sa.Enum('usuario', 'administrador', name='tipousuario'), nullable=True),
    sa.Column('status', sa.Enum('ativo', 'inativo', 'banido', name='statususuario'), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    op.create_index(op.f('ix_usuario_id_usuario'), 'usuario', ['id_usuario'], unique=False)
    op.create_table('area_restauracao',
    sa.Column('id_area', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('localizacao', sa.String(), nullable=True),
    sa.Column('cidade', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('bioma', sa.String(), nullable=True),
    sa.Column('area_aproximada', sa.Numeric(), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('percentual_progresso', sa.Numeric(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_area')
    )
    op.create_index(op.f('ix_area_restauracao_id_area'), 'area_restauracao', ['id_area'], unique=False)
    op.create_table('denuncia',
    sa.Column('id_denuncia', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('localizacao', sa.String(), nullable=True),
    sa.Column('cidade', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('latitude', sa.Numeric(), nullable=True),
    sa.Column('longitude', sa.Numeric(), nullable=True),
    sa.Column('data_ocorrencia', sa.Date(), nullable=True),
    sa.Column('gravidade', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('data_registro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_denuncia')
    )
    op.create_index(op.f('ix_denuncia_id_denuncia'), 'denuncia', ['id_denuncia'], unique=False)
    op.create_table('noticia',
    sa.Column('id_noticia', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(), nullable=True),
    sa.Column('conteudo', sa.Text(), nullable=True),
    sa.Column('imagem', sa.String(), nullable=True),
    sa.Column('data_publicacao', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_noticia')
    )
    op.create_index(op.f('ix_noticia_id_noticia'), 'noticia', ['id_noticia'], unique=False)
    op.create_table('ong',
    sa.Column('id_ong', sa.Integer(), nullable=False),
    sa.Column('id_usuario_cadastro', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('area_atuacao', sa.String(), nullable=True),
    sa.Column('site', sa.String(), nullable=True),
    sa.Column('link_doacao', sa.String(), nullable=True),
    sa.Column('redes_sociais', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario_cadastro'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_ong')
    )
    op.create_index(op.f('ix_ong_id_ong'), 'ong', ['id_ong'], unique=False)
    op.create_table('acao_restauracao',
    sa.Column('id_acao', sa.Integer(), nullable=False),
    sa.Column('id_area', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data_acao', sa.Date(), nullable=True),
    sa.Column('percentual_progresso', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['id_area'], ['area_restauracao.id_area'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_acao')
    )
    op.create_index(op.f('ix_acao_restauracao_id_acao'), 'acao_restauracao', ['id_acao'], unique=False)
    op.create_table('comentario',
    sa.Column('id_comentario', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_noticia', sa.Integer(), nullable=True),
    sa.Column('texto', sa.Text(), nullable=True),
    sa.Column('data_comentario', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_noticia'], ['noticia.id_noticia'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_comentario')
    )
    op.create_index(op.f('ix_comentario_id_comentario'), 'comentario', ['id_comentario'], unique=False)
    op.create_table('curtida',
    sa.Column('id_curtida', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_noticia', sa.Integer(), nullable=True),
    sa.Column('data_curtida', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_noticia'], ['noticia.id_noticia'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_curtida')
    )
    op.create_index(op.f('ix_curtida_id_curtida'), 'curtida', ['id_curtida'], unique=False)
    op.create_table('foto',
    sa.Column('id_foto', sa.Integer(), nullable=False),
    sa.Column('id_area', sa.Integer(), nullable=True),
    sa.Column('id_denuncia', sa.Integer(), nullable=True),
    sa.Column('url_foto', sa.String(), nullable=True),
    sa.Column('data_upload', sa.DateTime(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_area'], ['area_restauracao.id_area'], ),
    sa.ForeignKeyConstraint(['id_denuncia'], ['denuncia.id_denuncia'], ),
    sa.PrimaryKeyConstraint('id_foto')
    )
    op.create_index(op.f('ix_foto_id_foto'), 'foto', ['id_foto'], unique=False)
    op.create_table('historico_denuncia',
    sa.Column('id_historico', sa.Integer(), nullable=False),
    sa.Column('id_denuncia', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('status_anterior', sa.String(), nullable=True),
    sa.Column('novo_status', sa.String(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_denuncia'], ['denuncia.id_denuncia'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_historico')
    )
    op.create_index(op.f('ix_historico_denuncia_id_historico'), 'historico_denuncia', ['id_historico'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historico_denuncia_id_historico'), table_name='historico_denuncia')
    op.drop_table('historico_denuncia')
    op.drop_index(op.f('ix_foto_id_foto'), table_name='foto')
    op.drop_table('foto')
    op.drop_index(op.f('ix_curtida_id_curtida'), table_name='curtida')
    op.drop_table('curtida')
    op.drop_index(op.f('ix_comentario_id_comentario'), table_name='comentario')
    op.drop_table('comentario')
    op.drop_index(op.f('ix_acao_restauracao_id_acao'), table_name='acao_restauracao')
    op.drop_table('acao_restauracao')
    op.drop_index(op.f('ix_ong_id_ong'), table_name='ong')
    op.drop_table('ong')
    op.drop_index(op.f('ix_noticia_id_noticia'), table_name='noticia')
    op.drop_table('noticia')
    op.drop_index(op.f('ix_denuncia_id_denuncia'), table_name='denuncia')
    op.drop_table('denuncia')
    op.drop_index(op.f('ix_area_restauracao_id_area'), table_name='area_restauracao')
    op.drop_table('area_restauracao')
    op.drop_index(op.f('ix_usuario_id_usuario'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_table('usuario')
    # ### end Alembic commands ###
